name: Keploy Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Install Keploy
      run: |
        curl --silent --location 'https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz' | tar xz -C /tmp
        sudo mv /tmp/keploy /usr/local/bin/keploy
        sudo chmod +x /usr/local/bin/keploy

    - name: Keploy Test (Replay Recorded Tests)
      id: keploy-test
      continue-on-error: true
      run: |
        OUTPUT=$(sudo -E keploy test -c "go run main.go" --delay 30 --path ./ 2>&1) || echo "::set-output name=error::$OUTPUT"
        if [ $? -eq 0 ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
        fi
    
    - name: Comment PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const status = '${{ steps.keploy-test.outputs.status }}';
          const error = '${{ steps.keploy-test.outputs.error }}';
          
          const message = status === 'success' 
            ? '✅ Keploy tests passed successfully!'
            : `❌ Keploy tests failed:\n\`\`\`\n${error}\n\`\`\``;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });